/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import io.javalin.Javalin;
import io.javalin.core.JavalinConfig;
//import io.javalin.plugin.rendering.template.JavalinThymeleaf;

public class App {
    final String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Javalin app = getApp();
        app.start(getPort());
    }

    public static Javalin getApp() {
        Javalin app = Javalin.create(JavalinConfig::enableDevLogging);
        addRoutes(app);
        return app;
    }

    private static int getPort() {
        String port = System.getenv().getOrDefault("PORT", "5000");
        return Integer.parseInt(port);
    }

    private static void addRoutes(Javalin app) {
        // Для GET-запроса на маршрут / будет выполняться
        // обработчик welcome в контроллере RootController
        app.get("/", ctx -> ctx.result(new App().getGreeting()));

        // При помощи методов routes() и path() маршруты можно группировать

        // BEGIN
//        app.routes(() -> {
//            path("articles", () -> {
//                get(ArticleController.listArticles);
//                get("/new", ArticleController.newArticle);
//                get("{id}", ArticleController.showArticle);
//                post(ArticleController.createArticle);
//                get("/{id}/edit", ArticleController.editArticle);
//                post("/{id}/edit", ArticleController.updateArticle);
//                get("{id}/delete", ArticleController.deleteArticle);
//                post("{id}/delete", ArticleController.destroyArticle);
//            });
//        });
        // END
    }

}
